export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POST_DETAIL = 'GET_POST_DETAIL';
export const GET_POSTS_OF_USER = 'GET_POSTS_OF_USER';
export const GET_BOOKMARKED_POSTS_OF_USER = 'GET_BOOKMARKED_POSTS_OF_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
